name: envify
description: A better way to handle environment variables using `.env` file.
version: 2.0.2
homepage: https://github.com/frencojobs/envify

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lint: ^1.5.1
  test: ^1.16.8

scripts: ../derry.yaml
