name: envify
description: A better way to handle environment variables using `.env` file.
version: 2.0.2
homepage: https://github.com/frencojobs/envify

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  lint: ^1.8.1
  test: ^1.20.1

scripts: ../derry.yaml
