name: envify_generator
description: Code generator for envify, a better tool to handle environment variables.
version: 2.0.2
homepage: https://github.com/frencojobs/envify

publish_to: "none"

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  analyzer: ^4.0.0
  build: ^2.3.0
  dotenv: ^4.0.1
  envify:
    git:
      url: https://github.com/techouse/envify.git
      ref: main
      path: envify
  path: ^1.8.2
  source_gen: ^1.2.2

dev_dependencies:
  lint: ^1.8.2
  source_gen_test: ^1.0.2
  test: ^1.21.1

scripts: ../derry.yaml
