name: envify_generator
description: Code generator for envify, a better tool to handle environment variables.
version: 2.0.2
homepage: https://github.com/frencojobs/envify

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^3.3.0
  build: ^2.0.1
  dotenv: ^3.0.0
  envify: ^2.0.2
  path: ^1.8.0
  source_gen: ^1.0.0

dev_dependencies:
  lint: ^1.5.3
  source_gen_test: ^1.0.0
  test: ^1.16.8

scripts: ../derry.yaml
