name: envify_generator
description: Code generator for envify, a better tool to handle environment variables.
version: 2.0.2
homepage: https://github.com/frencojobs/envify

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  analyzer: ^3.0.0
  build: ^2.2.1
  dotenv: ^3.0.0
  envify: ^2.0.2
  path: ^1.8.1
  source_gen: ^1.2.1

dev_dependencies:
  lint: ^1.8.1
  source_gen_test: ^1.0.2
  test: ^1.20.1

scripts: ../derry.yaml
