name: example
version: 0.0.1
description: An example for envify.

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  envify:
    git:
      url: https://github.com/DebkanchanSamadder/envify.git
      path: envify

dev_dependencies:
  build_runner: ^2.0.0
  envify_generator:
    git:
      url: https://github.com/DebkanchanSamadder/envify.git
      path: envify_generator

dependency_overrides:
  envify:
    path: ../
  envify_generator:
    path: ../../envify_generator
